# Generated by Django 5.1 on 2024-08-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("divar", "0004_tempauthorizationdata_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempauthorizationdata",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tempauthorizationdata",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
