# Generated by Django 5.1 on 2024-08-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("divar", "0006_tempauthorizationdata_scopes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tempauthorizationdata",
            old_name="scopes",
            new_name="scope",
        ),
    ]
