# Generated by Django 5.1 on 2024-09-28 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divar', '0010_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('return_url', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=50)),
                ('post_token', models.CharField(blank=True, max_length=30, null=True)),
                ('user_side', models.CharField(blank=True, max_length=50, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
